version: '3'

services:
  faker-producer:
    container_name: faker-producer
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      ports: 7000:7000
      TOPIC_NAME: faker
      SLEEP_TIME: 5

networks:
  default:
    external: True
    name: kafka-network
